### ISSUE TITLE
Cannot find module "npm-cli" when running nyc in scripts

### ISSUE THREAD

**Issue by vKongv** [istanbuljs/nyc#760]
## Description
I encountered this error `Cannot find module ...../node_modules/.bin/npm/bin/npm-cli.js when running `nyc` in my `package.json` script commnad. I run the command using yarn with `yarn run test:cover`.

The script command look looks like this:
`"test:cover": "cross-env NODE_ENV=coverage nyc --reporter=lcov --reporter=text npm run test",`

The full error output is this
```
yarn run v1.1.0
$ cross-env NODE_ENV=coverage nyc --reporter=lcov --reporter=text npm run test
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\myproject\node_modules\.bin\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Function.Module.runMain (module.js:604:10)
    at runMain (C:\Users\kwkong\.node-spawn-wrap-11076-03c06d2900cd\node:68:10)
    at Function.<anonymous> (C:\Users\kwkong\.node-spawn-wrap-11076-03c06d2900cd\node:171:5)
    at Object.<anonymous> (C:\Users\kwkong\Documents\Repos\cpp-react\node_modules\nyc\bin\wrap.js:23:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Expected Behavior
Should run the command without error. 

## Observed Behavior
When I copy the command and run it directly in my CLI, it works fine. I suspect it is trying to access npm through my local `node_modules` when I tried to run it in my through script in my `package.json`.

## Forensic Information

**Operating System:** Window 10 Pro Version 1703
**Environment Information:**
https://gist.github.com/vKongv/f8862285cb2c2a3f99dfc16d2cd2b6a7

**Comment by bcoe** [comment]
would it be possible to provide a repo with a minimal reproduction of this issue? out of curiosity, does running:

`npm run test:cover` work as expected? I wonder if it might potentially be an incompatibility between npm and yarn.

**Comment by beeplin** [comment]
I encountered this issue to, and found this is caused by using `npm run test` after `nyc'. using `nyc mocha ....` directly is ok.

**Comment by nwayve** [comment]
In the spawn-wrap lib, there's a call to get the npm.cmd location:
https://github.com/tapjs/spawn-wrap/blob/master/index.js#L173

When I open a Node repl, perform a `which.sync('npm');`, I get the location `c:\\Program Files\\nodejs\\npm.CMD` as a result, but when I `console.log` out what the `npmPath` is on that line when running `npm test`, it's spitting out `{project_dir}\\node_modules\\.bin\\npm.CMD`.

In the clean project I started, when I do the same `console.log` on that `npmPath` variable, it spits out:
`c:\\Program Files\\nodejs\\npm.CMD`

Again, probably a misconfiguration somewhere but haven't nailed down what and where.

**Comment by nwayve** [comment]
Ok, I see what's going on now.
`spawn-wrap` uses the `which` npm lib to find the directory the `npm` command is located at looking at the `path` environment variable.  The path environment variable, for me, is getting the `{cwd}`, `{cwd}/node_modules/npm-lifecycle/node-gyp-bin`, and `{cwd}/node_modules/.bin` directories unshifted into the path environment variable.
When it looks for the `npm` CMD in Windows, it finds it in the `{cwd}/node_modules/.bin` directory and returns that directory.  `spawn-wrap` then appends `/node_modules/npm/bin/npm-cli.js` to that path.

Well, in that instance, that's an invalid path and is why we see the error:
```Error: Cannot find module '{cwd}\node_modules\.bin\node_modules\npm\bin\npm-cli.js'```

It also explains why, in the "clean" project, this isn't happening.  The `npm` CMD isn't installed in the `node_modules/.bin` directory.

So this feels like an issue with `spawn-wrap` assuming the `/node_modules/npm/bin/npm-cli.js` directory will be there.

**Comment by nwayve** [comment]
Found the culprit on my end with the "misconfiguration".  This all started when I updated node from 9 to 10 and updated npm from 5 to 6.  I did this in the project's directory which I inadvertently installed npm as a dependency to the project.  This in turn added the `npm` CMD file to the `node_modules/.bin` directory.

Removing that dependency, deleting the node_modules, and doing a clean `npm install` fixed the issue.

**Comment by lukasmatta** [comment]
Removing _npm_ file from _/node_modules/.bin/ folder helped me.
